version: "3.9"

services:
  api:
    container_name: minha_api
    build:
      context: ./src/Gerenciador.Noticias/Gerenciador.Noticias.Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: meu_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
